name: kudog
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5-131.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 6.0.4
  dio: ^4.0.6
  http: ^0.13.6
  http_parser: ^4.0.2
  shared_preferences: any
  flutter_secure_storage: ^5.0.2
  flutter_widget_from_html: ^0.14.10
  flutter_downloader: ^1.11.6
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans-Regular
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: ReadexPro-Regular
      fonts:
        - asset: assets/fonts/ReadexPro-Regular.ttf
  assets:
    - assets/images/
