name: kudog
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: "3.1.5"

dependencies:
  flutter:
    sdk: flutter
  provider: 6.0.4
  dio: ^4.0.6
  http: ^0.13.6
  http_parser: ^4.0.2
  flutter_html: ^3.0.0-alpha.6
  charcode: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans-Regular
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: ReadexPro-Regular
      fonts:
        - asset: assets/fonts/ReadexPro-Regular.ttf
  assets:
    - assets/images/
